import = [
    "~/.config/alacritty/gruvbox_dark.toml",
    # "~/.config/alacritty/catppuccin-mocha.toml",
    "~/.config/alacritty/font.toml",
    "~/.config/alacritty/window.toml",
    "~/.config/alacritty/selection.toml",
]
